Repository TeamBulbbot/bulbbot, pull requests merged in 2021-12, with the labels that each got.

#281 Bug fixes
  src/commands/Admin/blacklist.ts
  src/commands/Configuration/configure/automod/settings.ts
  src/commands/Configuration/configure/quickReasons/add.ts
  src/commands/Configuration/settings.ts
  src/commands/Configuration/setup.ts
  src/commands/Configuration/setup/automod.ts
  src/commands/Moderation/infraction/info.ts
  src/commands/Moderation/infraction/modsearch.ts
  src/commands/Moderation/infraction/offendersearch.ts
  src/commands/Moderation/infraction/remove.ts
  src/commands/Moderation/infraction/search.ts
  src/commands/Moderation/purge/all.ts
  src/commands/Moderation/purge/between.ts
  src/commands/Moderation/purge/bots.ts
  src/commands/Moderation/purge/contains.ts
  src/commands/Moderation/purge/embeds.ts
  src/commands/Moderation/purge/emojis.ts
  src/commands/Moderation/purge/images.ts
  src/commands/Moderation/purge/user.ts
  src/events/guild/channels/channelDelete.ts
  src/events/guild/roles/roleDelete.ts
  src/events/guild/roles/roleUpdate.ts
  src/interactions/context/infSearch.ts
  src/interactions/select/infraction.ts
  src/structures/Command.ts
  src/structures/Util.ts
  src/utils/AutoMod.ts
  src/utils/Regex.ts
  src/utils/managers/ClearanceManager.ts
  src/utils/managers/DatabaseManager.ts
  src/utils/managers/InfractionsManager.ts
  src/utils/managers/LoggingManager.ts
  src/utils/types/AutoModConfiguration.ts
  src/utils/types/DatabaseStructures.ts
  src/utils/types/GuildConfiguration.ts
  src/utils/types/Infraction.ts
  src/utils/types/LoggingConfiguration.ts
Labels: bug, enhancement, internal

#286 package updates
  package-lock.json
  package.json
  src/structures/CommandContext.ts
  yarn.lock
Labels: dependencies, internal

#287 fix(Regex): invite regex flags valid text
  src/utils/Regex.ts
Labels: bug, automod

#289 update(Mute) adds the new timeout feature to the bot
  src/commands/Moderation/mute.ts
  src/commands/Moderation/unmute.ts
  src/events/message/messageCreate.ts
  src/interactions/context/mute.ts
  src/languages/en-US.json
  src/utils/Restoration.ts
  src/utils/managers/InfractionsManager.ts
Labels: enhancement

#294 Migration to timeouts
  package-lock.json
  src/commands/Moderation/mute.ts
  src/commands/Moderation/unmute.ts
  src/events/bot/ready.ts
  src/events/guild/channels/channelCreate.ts
  src/events/guild/channels/channelDelete.ts
  src/events/guild/channels/channelUpdate.ts
  src/events/guild/channels/inviteDelete.ts
  src/events/guild/guildBanAdd.ts
  src/events/guild/guildBanRemove.ts
  src/events/guild/guildUpdate.ts
  src/events/guild/member/guildMemberAdd.ts
  src/events/guild/member/guildMemberRemove.ts
  src/events/guild/member/guildMemberUpdate.ts
  src/events/message/messageDelete.ts
  src/interactions/context/mute.ts
  src/languages/en-US.json
  src/structures/CommandContext.ts
  src/utils/Restoration.ts
  src/utils/database/applyExtra.ts
  src/utils/database/connection.ts
  src/utils/database/models/Tempmute.ts
  src/utils/managers/InfractionsManager.ts
  src/utils/managers/MuteManger.ts
  yarn.lock
Labels: enhancement

#293 Bot/improve a lot of places
  interactionCommands.json
  src/Config.ts
  src/commands/Configuration/settings.ts
  src/commands/Information/badges.ts
  src/commands/Information/channelinfo.ts
  src/commands/Information/inviteinfo.ts
  src/commands/Information/messageinfo.ts
  src/commands/Information/roleinfo.ts
  src/commands/Information/server.ts
  src/commands/Information/userinfo.ts
  src/commands/Miscellaneous/id.ts
  src/commands/Miscellaneous/snowflake.ts
  src/commands/Moderation/prune.ts
  src/commands/Moderation/purge.ts
  src/commands/Moderation/purge/all.ts
  src/commands/Moderation/purge/between.ts
  src/commands/Moderation/purge/bots.ts
  src/commands/Moderation/purge/contains.ts
  src/commands/Moderation/purge/embeds.ts
  src/commands/Moderation/purge/emojis.ts
  src/commands/Moderation/purge/images.ts
  src/commands/Moderation/purge/until.ts
  src/commands/Moderation/purge/user.ts
  src/emotes.json
  src/languages/en-US.json
  src/utils/BulbBotUtils.ts
  src/utils/Regex.ts
  src/utils/managers/LoggingManager.ts
Labels: enhancement

#280 DB Message logs
  package.json
  src/Config.ts
  src/commands/Admin/admin/database.ts
  src/commands/Admin/admin/database/clearmessages.ts
  src/commands/Configuration/messageclear.ts
  src/commands/Moderation/archive.ts
  src/commands/Moderation/archive/channel.ts
  src/commands/Moderation/archive/user.ts
  src/emotes.json
  src/events/message/messageCreate.ts
  src/events/message/messageDelete.ts
  src/events/message/messageUpdate.ts
  src/index.ts
  src/languages/en-US.json
  src/structures/BulbBotClient.ts
  src/structures/CommandContext.ts
  src/utils/Crons.ts
  src/utils/database/applyExtra.ts
  src/utils/database/connection.ts
  src/utils/database/models/MessageLogs.ts
  src/utils/managers/DatabaseManager.ts
  yarn.lock
Labels: internal
