Repository TeamBulbbot/bulbbot, pull requests merged in 2021-08, with the labels that each got.

#164 Update clearance handler
  src/languages/en-US.json
  src/structures/Command.ts
Labels: bug, security

#171 Added the ability to change server language
  interactionCommands.json
  src/commands/Configuration/configure.ts
  src/commands/Configuration/configure/language.ts
  src/utils/BulbBotUtils.ts
Labels: enhancement, translation

#167 Full Slovak Translation
  src/index.ts
  src/languages/sk-SK.json
  src/utils/BulbBotUtils.ts
Labels: translation

#165 Fix inability to create overrides with clearance 0
  src/commands/Admin/command/reload.ts
  src/commands/Configuration/configure/override.ts
  src/commands/Configuration/configure/override/create.ts
  src/commands/Configuration/configure/override/edit.ts
  src/languages/en-US.json
  src/structures/BulbBotClient.ts
Labels: bug

#181 Role logging when members leave
  .github/CODEOWNERS
  interactionCommands.json
  src/commands/Configuration/configure.ts
  src/commands/Configuration/configure/rolesOnLeave.ts
  src/commands/Configuration/settings.ts
  src/events/guild/member/guildMemberRemove.ts
  src/languages/en-US.json
  src/utils/database/models/GuildConfiguration.ts
  src/utils/managers/DatabaseManager.ts
Labels: enhancement

#180 Refactor logging but without the bug
  src/events/guild/channels/channelUpdate.ts
  src/events/guild/guildUpdate.ts
  src/events/guild/member/guildMemberAdd.ts
  src/events/guild/member/guildMemberRemove.ts
  src/events/guild/roles/roleUpdate.ts
  src/events/message/messageDelete.ts
  src/events/message/messageUpdate.ts
  src/languages/en-US.json
  src/utils/managers/LoggingManager.ts
  src/utils/types/LoggingPart.ts
Labels: enhancement

#156 Czech Translation
  interactionCommands.json
  src/index.ts
  src/languages/cs-CZ.json
  src/languages/en-US.json
  src/utils/BulbBotUtils.ts
Labels: translation
