Repository TeamBulbbot/bulbbot, pull requests merged in 2021-09, with the labels that each got.

#194 Fix some incorrect variable references
  src/languages/sk-SK.json
Labels: bug

#210 I18n updates
  interactionCommands.json
  src/index.ts
  src/languages/fr-FR.json
  src/languages/it-IT.json
  src/utils/BulbBotUtils.ts
Labels: translation

#209 Remove DIRECT_MESSAGES intent
  src/Config.ts
  src/events/message/messageCreate.ts
  src/utils/DMUtils.ts
Labels: enhancement

#220 Improve error logging when thrown in an event
  src/structures/Util.ts
  src/utils/BulbBotUtils.ts
Labels: enhancement

#221 Missing perms error fix
  src/events/message/messageCreate.ts
Labels: bug

#208 Admin updates
  .github/ISSUE_TEMPLATE/bug_report.md
  package-lock.json
  package.json
  src/Config.ts
  src/commands/Admin/admin.ts
  src/commands/Admin/admin/botfarm.ts
  src/commands/Admin/eval.ts
  src/commands/Bot/ping.ts
  src/events/message/messageCreate.ts
  src/index.ts
  yarn.lock
Labels: enhancement

#219 roleUpdate fix
  src/events/guild/roles/roleUpdate.ts
  src/languages/en-US.json
  src/utils/BulbBotUtils.ts
Labels: enhancement

#235 Fix log bugs
  src/structures/CommandContext.ts
  src/structures/Util.ts
  src/utils/AutoMod.ts
Labels: enhancement

#227 Permissions command
  src/commands/Miscellaneous/permissions.ts
  src/languages/en-US.json
Labels: enhancement
