Repository TeamBulbbot/bulbbot, pull requests merged in 2021-10, with the labels that each got.

#245 i18n/workflow
  .github/workflows/crowdin.yml
  crowdin.yml
Labels: translation

#256 Automatic muterole setup
  src/commands/Configuration/configure/muterole.ts
  src/events/guild/channels/channelCreate.ts
  src/utils/BulbBotUtils.ts
Labels: enhancement

#262 Bug fixes related to the new website + name change
  README.md
  package.json
  src/events/bot/ready.ts
  src/events/message/messageCreate.ts
  src/languages/cs-CZ.json
  src/languages/en-US.json
  src/languages/fr-FR.json
  src/languages/hi-IN.json
  src/languages/it-IT.json
  src/languages/pt-BR.json
  src/languages/sk-SK.json
  src/languages/sv-SE.json
  src/utils/BulbBotUtils.ts
Labels: bug

#278 Improved context menus
  interactionCommands.json
  src/commands/Configuration/configure.ts
  src/commands/Configuration/configure/quickReasons.ts
  src/commands/Configuration/configure/quickReasons/add.ts
  src/commands/Configuration/configure/quickReasons/remove.ts
  src/commands/Configuration/settings.ts
  src/events/bot/interactionCreate.ts
  src/interactions/context/ban.ts
  src/interactions/context/infSearch.ts
  src/interactions/context/kick.ts
  src/interactions/context/mute.ts
  src/interactions/context/warn.ts
  src/languages/en-US.json
  src/utils/database/models/GuildConfiguration.ts
  src/utils/managers/DatabaseManager.ts
  src/utils/types/GuildConfiguration.ts
  src/utils/types/TranslateString.ts
Labels: enhancement
