Repository TeamBulbbot/bulbbot, pull requests merged in 2022-05, with the labels that each got.

#361 feat: made the manuel infractions a toggle
  src/commands/Configuration/configure.ts
  src/commands/Configuration/configure/main.ts
  src/commands/Configuration/configure/manuelNicknameInf.ts
  src/commands/Configuration/settings.ts
  src/events/guild/member/guildMemberUpdate.ts
  src/languages/en-US.json
  src/languages/en-US.ts
  src/utils/database/models/GuildConfiguration.ts
  src/utils/managers/DatabaseManager.ts
  src/utils/types/DatabaseStructures.ts
Labels: enhancement

#360 bug: add the missing slashcommand for snowflake
  src/utils/InteractionCommands.ts
Labels: bug

#358 bug: added the missing slash command for banpools
  src/utils/InteractionCommands.ts
Labels: bug

#357 bug: add in messageinfo because it was hidden behind experiment tag
  src/commands/Information/messageinfo.ts
Labels: bug

#362 typo: manual nickname infractions
  src/commands/Configuration/configure.ts
  src/commands/Configuration/configure/main.ts
  src/commands/Configuration/configure/manuelNicknameInf.ts
  src/commands/Configuration/settings.ts
  src/events/guild/member/guildMemberUpdate.ts
  src/languages/en-US.json
  src/languages/en-US.ts
  src/utils/database/models/GuildConfiguration.ts
  src/utils/managers/DatabaseManager.ts
  src/utils/types/DatabaseStructures.ts
Labels: bug

#356 chore: rename server to serverinfo
  src/commands/Information/serverinfo.ts
Labels: enhancement

#368 Fix nodemon hotreloading to run the language script too
  package.json
Labels: internal

#369 Misc util stuff
  src/utils/BulbBotUtils.ts
  src/utils/helpers.ts
Labels: subsystems

#370 Avoid splitting the nickname argument passed in slash command
  src/commands/Moderation/nickname.ts
  src/events/bot/interactionCreate.ts
Labels: subsystems
