Repository TeamBulbbot/bulbbot, pull requests merged in 2022-08, with the labels that each got.

#392 Fix roleUpdate
  src/events/guild/roles/roleUpdate.ts
Labels: logging

#393 Refactor bulbfetch & fix messageDelete errors
  src/events/message/messageDelete.ts
  src/utils/BulbBotFetch.ts
Labels: logging

#394 Remove legacy code (prefix and mute roles)
  src/Config.ts
  src/commands/Configuration/configure.ts
  src/commands/Configuration/configure/main.ts
  src/events/guild/roles/roleDelete.ts
  src/events/guild/roles/roleUpdate.ts
  src/events/message/messageCreate.ts
  src/index.ts
  src/languages/en-US.json
  src/languages/en-US.ts
  src/prisma/migrations/20220818104256_remove_prefix_and_muterole/migration.sql
  src/prisma/schema.prisma
  src/structures/BulbBotClient.ts
  src/utils/managers/DatabaseManager.ts
  src/utils/types/ConfigPart.ts
  src/utils/types/GuildSetup.ts
Labels: bug, internal

#395 Reorganize interactionCreate to get rid of typecasting
  src/events/bot/interactionCreate.ts
Labels: subsystems

#396 Prefer fs promises over fs sync API
  src/commands/Miscellaneous/jumbo.ts
  src/commands/Moderation/archive/channel.ts
  src/commands/Moderation/archive/user.ts
  src/commands/Moderation/purge/all.ts
  src/commands/Moderation/purge/between.ts
  src/commands/Moderation/purge/bots.ts
  src/commands/Moderation/purge/contains.ts
  src/commands/Moderation/purge/embeds.ts
  src/commands/Moderation/purge/emojis.ts
  src/commands/Moderation/purge/images.ts
  src/commands/Moderation/purge/until.ts
  src/commands/Moderation/purge/user.ts
  src/events/message/messageDelete.ts
  src/events/message/messageUpdate.ts
  src/index.ts
  src/utils/helpers.ts
Labels: subsystems

#405 Bug fixes 03
  .gitignore
  package.json
  scripts/writeEnUsJson.js
  src/Config.ts
  src/commands/Admin/eval.ts
  src/commands/Bot/about.ts
  src/commands/Configuration/banpool/delete.ts
  src/commands/Configuration/banpool/remove.ts
  src/commands/Configuration/configure/actionsOnInfo.ts
  src/commands/Configuration/configure/automod.ts
  src/commands/Configuration/configure/autorole.ts
  src/commands/Configuration/configure/language.ts
  src/commands/Configuration/configure/logging.ts
  src/commands/Configuration/configure/main.ts
  src/commands/Configuration/configure/manualNicknameInf.ts
  src/commands/Configuration/configure/quickReasons.ts
  src/commands/Configuration/configure/rolesOnLeave.ts
  src/commands/Configuration/configure/timezone.ts
  src/commands/Configuration/messageclear.ts
  src/commands/Context/clean.ts
  src/commands/Information/inviteinfo.ts
  src/commands/Information/userinfo.ts
  src/commands/Miscellaneous/jumbo.ts
  src/commands/Moderation/archive/channel.ts
  src/commands/Moderation/archive/user.ts
  src/commands/Moderation/ban.ts
  src/commands/Moderation/crossban.ts
  src/commands/Moderation/deafen.ts
  src/commands/Moderation/infraction/remove.ts
  src/commands/Moderation/kick.ts
  src/commands/Moderation/mute.ts
  src/commands/Moderation/nickname.ts
  src/commands/Moderation/prune.ts
  src/commands/Moderation/purge/all.ts
  src/commands/Moderation/purge/between.ts
  src/commands/Moderation/purge/bots.ts
  src/commands/Moderation/purge/contains.ts
  src/commands/Moderation/purge/embeds.ts
  src/commands/Moderation/purge/emojis.ts
  src/commands/Moderation/purge/images.ts
  src/commands/Moderation/purge/until.ts
  src/commands/Moderation/purge/user.ts
  src/commands/Moderation/tempban.ts
  src/commands/Moderation/undeafen.ts
  src/commands/Moderation/unmute.ts
  src/commands/Moderation/warn.ts
  src/events/message/messageDelete.ts
  src/events/message/messageUpdate.ts
  src/index.ts
  src/languages/en-US.json
  src/languages/en-US.ts
  src/utils/Crons.ts
  tsconfig.json
Labels: bug, translation, internal

#407 bug: fixes a bug with crossban when a guild was not subscribed to anything
  src/commands/Moderation/crossban.ts
  src/languages/en-US.json
  src/languages/en-US.ts
Labels: bug

#409 More command analytics
  src/events/bot/interactionCreate.ts
  src/utils/Prometheus.ts
Labels: internal

#411 feat: change the response on interactions on jumbo
  src/commands/Miscellaneous/jumbo.ts
Labels: enhancement
