Repository TeamBulbbot/bulbbot, pull requests merged in 2022-06, with the labels that each got.

#373 bug: add parsing to the immune automod
  src/commands/Configuration/configure/automod/add.ts
  src/languages/en-US.json
  src/languages/en-US.ts
Labels: bug

#372 chore: remove npm
  package-lock.json
  package.json
Labels: internal

#382 Change some DB types
  .lintstagedrc.js
  package.json
  src/commands/Moderation/infraction/info.ts
  src/events/guild/member/guildMemberUpdate.ts
  src/events/message/messageCreate.ts
  src/interactions/select/infraction.ts
  src/prisma/migrations/20220625160923_active_to_boolean/migration.sql
  src/prisma/migrations/20220625162546_non_nullable_booleans/migration.sql
  src/prisma/migrations/20220625165700_punishment_enum/migration.sql
  src/prisma/migrations/20220625192345_non_nullable_bulb_guild/migration.sql
  src/prisma/migrations/20220625192746_drop_override_models/migration.sql
  src/prisma/schema.prisma
  src/utils/managers/BanpoolManager.ts
  src/utils/managers/DatabaseManager.ts
  src/utils/managers/InfractionsManager.ts
Labels: subsystems

#383 bug: makes avatar banning possible
  src/commands/Configuration/configure/automod/add.ts
  src/languages/en-US.json
  src/languages/en-US.ts
Labels: bug, automod
