Repository TeamBulbbot/bulbbot, pull requests merged in 2022-02, with the labels that each got.

#313 fix: loads all language files from the lang folder
  src/index.ts
Labels: internal

#314 update/internal: added support for animated emojis + bumped packages because we had to that for this to work
  package-lock.json
  package.json
  src/commands/Miscellaneous/jumbo.ts
  src/languages/en-US.json
  yarn.lock
Labels: enhancement, internal

#317 bug: fixed 2 jumbo bugs
  src/commands/Miscellaneous/jumbo.ts
Labels: bug

#318 add events support for scheduled events
  src/Config.ts
  src/events/guild/scheduledEvents/guildScheduledEventCreate.ts
  src/events/guild/scheduledEvents/guildScheduledEventDelete.ts
  src/events/guild/scheduledEvents/guildScheduledEventUpdate.ts
  src/languages/en-US.json
Labels: enhancement, logging

#326 bug/ench: day 1 bug fixes of the avatar hashes automod feature
  src/commands/Configuration/configure/automod/add.ts
  src/commands/Configuration/configure/automod/remove.ts
  src/events/guild/member/guildMemberAdd.ts
  src/languages/en-US.json
  src/utils/managers/LoggingManager.ts
Labels: bug, enhancement, automod

#332 feat: adds the spammer flag to the userinfo command
  src/emotes.json
  src/utils/BulbBotUtils.ts
Labels: enhancement
