Repository TeamBulbbot/bulbbot, pull requests merged in 2022-04, with the labels that each got.

#346 Fix valueOf error & improve diff implementation
  src/utils/BulbBotUtils.ts
Labels: subsystems

#344 TranslateOptions type
  .lintstagedrc.js
  package.json
  scripts/writeEnUsJson.js
  src/commands/Configuration/banpool/join.ts
  src/commands/Configuration/banpool/leave.ts
  src/commands/Configuration/configure.ts
  src/commands/Configuration/configure/automod/overview.ts
  src/commands/Configuration/configure/autorole.ts
  src/commands/Configuration/configure/main.ts
  src/commands/Information/userinfo.ts
  src/commands/Moderation/cleanban.ts
  src/commands/Moderation/crossban.ts
  src/commands/Moderation/infraction/claim.ts
  src/commands/Moderation/infraction/info.ts
  src/commands/Moderation/infraction/remove.ts
  src/commands/Moderation/infraction/update.ts
  src/commands/Moderation/lockdown.ts
  src/commands/Moderation/mute.ts
  src/commands/Moderation/nickname.ts
  src/commands/Moderation/tempban.ts
  src/events/guild/channels/channelCreate.ts
  src/events/guild/channels/channelDelete.ts
  src/events/guild/channels/channelUpdate.ts
  src/events/guild/channels/inviteDelete.ts
  src/events/guild/guildUpdate.ts
  src/events/guild/member/guildMemberUpdate.ts
  src/events/guild/scheduledEvents/guildScheduledEventCreate.ts
  src/events/guild/scheduledEvents/guildScheduledEventDelete.ts
  src/events/guild/scheduledEvents/guildScheduledEventUpdate.ts
  src/events/message/messageDelete.ts
  src/interactions/context/mute.ts
  src/interactions/context/warn.ts
  src/interactions/select/infraction.ts
  src/interactions/select/reminders.ts
  src/languages/en-US.json
  src/languages/en-US.ts
  src/structures/AutoModCache.ts
  src/utils/BulbBotUtils.ts
  src/utils/Restoration.ts
  src/utils/managers/AutoModManager.ts
  src/utils/managers/InfractionsManager.ts
  src/utils/managers/LoggingManager.ts
  src/utils/types/TranslateOptions.ts
  src/utils/types/TranslateString.ts
  tsconfig.json
Labels: enhancement, translation, subsystems, internal

#349 bug: fixes the mute bug 348
  src/commands/Moderation/mute.ts
Labels: bug

#353 fix: swapped to different http server because vps did not like node-server
  package.json
  src/utils/Prometheus.ts
  yarn.lock
Labels: internal

#355 Fix #354
  src/commands/Configuration/configure/autorole.ts
Labels: bug, p1
